version: 0.2

phases:
  install:
    runtime-versions:
      docker: latest
      python: latest  
    commands:
  pre_build:
    commands:
      - echo Installing source dependencies...
      - pip install -r requirements.txt
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG> imagedefinition.js
  post_build:
    commands:
      - echo pushing the docker image
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"%s", "imageUri":"%s"}]' $CONTAINER_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$$IMAGE_REPO_NAME:$IMAGE_TAG> imagedefinition.js
artifacts:
  files: imagedefinition.json