version: 0.2

phases:
  install:
    runtime-versions:
      python: latest  
    commands:
  pre_build:
    commands:
      - echo Installing source dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - python main.py
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 287269600687.dkr.ecr.eu-central-1.amazonaws.com
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 287269600687.dkr.ecr.eu-central-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo pushing the docker image
      - docker push 287269600687.dkr.ecr.eu-central-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"%s", "imageUri":"%s"}]' $CONTAINER_NAME 287269600687.dkr.ecr.eu-central-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json