# Generated by Django 4.0.3 on 2022-04-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(default=-1)),
                ('message', models.CharField(max_length=5096)),
                ('hour', models.IntegerField(default=-1)),
                ('minute', models.IntegerField(default=-1)),
                ('second', models.IntegerField(default=-1)),
                ('score_1', models.IntegerField(default=-1)),
                ('score_2', models.IntegerField(default=-1)),
            ],
        ),
    ]
