# Generated by Django 4.0.3 on 2022-04-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimessage',
            name='hour',
            field=models.CharField(default=-1, max_length=2),
        ),
        migrations.AlterField(
            model_name='apimessage',
            name='minute',
            field=models.CharField(default=-1, max_length=2),
        ),
        migrations.AlterField(
            model_name='apimessage',
            name='second',
            field=models.CharField(default=-1, max_length=2),
        ),
    ]
