# Generated by Django 4.0.3 on 2022-03-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(blank=True, max_length=512)),
                ('language_code', models.CharField(default='uk', max_length=512)),
                ('password_id', models.IntegerField(default=-1)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('current_screen_code', models.CharField(default='uk', max_length=512)),
                ('screen_messages_ids', models.CharField(default='', max_length=512)),
                ('remainders_ids', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasword_sha256', models.CharField(max_length=512)),
                ('user_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='TextString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_id', models.CharField(default='', max_length=512)),
                ('position_index', models.IntegerField(default=-1)),
                ('uk', models.CharField(blank=True, max_length=512)),
                ('en', models.CharField(blank=True, max_length=512)),
            ],
        ),
    ]
