# Generated by Django 4.0.3 on 2022-03-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(default=';', max_length=512)),
                ('status', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=512)),
                ('events_ids', models.CharField(default=';', max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
