# Generated by Django 4.0.3 on 2022-04-28 14:17

from django.db import migrations, models
import tg_bot.models.CharableListField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RulesSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(default='{}', max_length=5096)),
                ('status', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=5096)),
                ('win_event_by', models.IntegerField(default=0)),
                ('win_period_by', tg_bot.models.CharableListField.CharableListField()),
                ('periods_in_event', models.IntegerField(default=2)),
                ('periods_to_win_event', models.IntegerField(default=2)),
                ('points_in_period', models.IntegerField(default=2)),
                ('points_to_win_period', tg_bot.models.CharableListField.CharableListField()),
                ('stop_event_after_enough_periods', models.IntegerField(default=0)),
                ('stop_period_after_enough_points', tg_bot.models.CharableListField.CharableListField()),
                ('min_difference_periods_to_win_event', models.IntegerField(default=0)),
                ('min_difference_points_to_win_period', tg_bot.models.CharableListField.CharableListField()),
                ('points_per_period_per_score_per_team', tg_bot.models.CharableListField.CharableListField()),
                ('scores_names', tg_bot.models.CharableListField.CharableListField()),
                ('ball_control_after_score_per_score', tg_bot.models.CharableListField.CharableListField()),
                ('pause_after_score_per_score', tg_bot.models.CharableListField.CharableListField()),
                ('event_length_minutes', models.IntegerField(default=0)),
                ('periods_lenght_minutes', tg_bot.models.CharableListField.CharableListField()),
                ('interval_between_periods_munutes', tg_bot.models.CharableListField.CharableListField()),
                ('event_timer_direction', models.IntegerField(default=0)),
                ('period_timers_directions', tg_bot.models.CharableListField.CharableListField()),
                ('event_timer_stops_at_pauses', models.IntegerField(default=0)),
                ('period_timers_stop_at_pauses', tg_bot.models.CharableListField.CharableListField()),
                ('side_changes_after_periods', tg_bot.models.CharableListField.CharableListField()),
                ('side_changes_during_periods', tg_bot.models.CharableListField.CharableListField()),
                ('side_changes_during_periods_scores', tg_bot.models.CharableListField.CharableListField()),
                ('coin_tosses_before_periods', tg_bot.models.CharableListField.CharableListField()),
                ('coin_toss_start_before_minutes', tg_bot.models.CharableListField.CharableListField()),
                ('time_outs_per_team_per_period', tg_bot.models.CharableListField.CharableListField()),
                ('time_outs_lenghts_per_team_per_period', tg_bot.models.CharableListField.CharableListField()),
                ('technical_time_outs_lenghts_per_period', tg_bot.models.CharableListField.CharableListField()),
                ('technical_time_outs_at_score_per_period', tg_bot.models.CharableListField.CharableListField()),
                ('actions_list', tg_bot.models.CharableListField.CharableListField()),
                ('event_start_remainder_minutes_before', tg_bot.models.CharableListField.CharableListField()),
                ('event_end_remainder_minutes_before', tg_bot.models.CharableListField.CharableListField()),
                ('period_start_remainder_minutes_before', tg_bot.models.CharableListField.CharableListField()),
                ('period_end_remainder_minutes_before', tg_bot.models.CharableListField.CharableListField()),
                ('coin_toss_remainder_minutes_before', tg_bot.models.CharableListField.CharableListField()),
            ],
            options={
                'abstract': False,
            },
        )
    ]
