# Generated by Django 4.0.3 on 2022-04-28 22:33

from django.db import migrations, models
import tg_bot.models.CharableListField


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesset',
            name='points_in_period',
            field=tg_bot.models.CharableListField.CharableListField(),
        ),
    ]
