# Generated by Django 4.0.3 on 2022-05-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='blocked_for_new_requests',
            field=models.IntegerField(default=0),
        ),
    ]
