# Generated by Django 4.0.3 on 2022-03-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textstring',
            old_name='en',
            new_name='language_1',
        ),
        migrations.RenameField(
            model_name='textstring',
            old_name='uk',
            new_name='language_2',
        ),
        migrations.AddField(
            model_name='textstring',
            name='language_3',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='textstring',
            name='language_4',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='textstring',
            name='language_5',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='remainders_ids',
            field=models.CharField(default='()', max_length=512),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='screen_messages_ids',
            field=models.CharField(default='()', max_length=512),
        ),
    ]
