# Generated by Django 4.0.3 on 2022-03-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(blank=True, max_length=512)),
                ('language_id', models.IntegerField(default=0)),
                ('password_id', models.IntegerField(default=-1)),
                ('is_logged_in', models.IntegerField(default=0)),
                ('is_superadmin', models.IntegerField(default=0)),
                ('current_screen_code', models.CharField(default='00', max_length=512)),
                ('screen_messages_ids', models.CharField(default='{}', max_length=512)),
                ('remainders_ids', models.CharField(default='{}', max_length=512)),
                ('user_input_messages_ids', models.CharField(default='{}', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(default=';', max_length=512)),
                ('status', models.IntegerField(default=0)),
                ('admin_id', models.IntegerField(default=-1)),
                ('competition_id', models.IntegerField(default=-1)),
                ('rules_set_id', models.IntegerField(default=-1)),
                ('date_scheduled', models.CharField(default='', max_length=5096)),
                ('time_scheduled', models.CharField(default='', max_length=5096)),
                ('date_actual', models.CharField(default='', max_length=5096)),
                ('time_actual', models.CharField(default='', max_length=5096)),
                ('home_team_id', models.IntegerField(default=-1)),
                ('away_team_id', models.IntegerField(default=-1)),
                ('periods_ids', models.CharField(default=';', max_length=5096)),
                ('coin_toss_ids', models.CharField(default=';', max_length=5096)),
                ('timer_ids', models.CharField(default=';', max_length=5096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_sha256', models.CharField(max_length=512)),
                ('user_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='RulesSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(default=';', max_length=512)),
                ('status', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=512)),
                ('win_event_by', models.IntegerField(default=0)),
                ('win_period_by', models.CharField(default=';', max_length=512)),
                ('periods_in_event', models.IntegerField(default=2)),
                ('periods_to_win_event', models.IntegerField(default=2)),
                ('points_in_period', models.IntegerField(default=2)),
                ('points_to_win_period', models.CharField(default=';', max_length=512)),
                ('stop_event_after_enough_periods', models.BooleanField(default=False)),
                ('stop_period_after_enough_points', models.BooleanField(default=False)),
                ('min_difference_periods_to_win_event', models.IntegerField(default=0)),
                ('min_difference_points_to_win_period', models.CharField(default=';', max_length=512)),
                ('points_per_score_per_period', models.CharField(default=';', max_length=512)),
                ('scores_names', models.CharField(default=';', max_length=512)),
                ('event_length_minutes', models.IntegerField(default=0)),
                ('periods_lenght_minutes', models.CharField(default=';', max_length=512)),
                ('interval_between_periods_munutes', models.CharField(default=';', max_length=512)),
                ('event_timer_direction', models.IntegerField(default=0)),
                ('period_timers_directions', models.CharField(default=';', max_length=512)),
                ('event_timer_stops_at_pauses', models.BooleanField(default=False)),
                ('period_timers_stop_at_pauses', models.CharField(default=';', max_length=512)),
                ('side_changes_after_periods', models.CharField(default=';', max_length=512)),
                ('side_changes_during_periods', models.CharField(default=';', max_length=512)),
                ('side_changes_during_periods_scores', models.CharField(default=';', max_length=512)),
                ('side_changes_during_periods_pause_time_seconds', models.CharField(default=';', max_length=512)),
                ('coin_tosses_before_periods', models.CharField(default=';', max_length=512)),
                ('coin_toss_start_before_minutes', models.CharField(default=';', max_length=512)),
                ('time_outs_per_team_per_period', models.CharField(default=';', max_length=512)),
                ('time_outs_lenghts_per_team_per_period', models.CharField(default=';', max_length=512)),
                ('technical_time_outs_lenghts_per_period', models.CharField(default=';', max_length=512)),
                ('technical_time_outs_at_score_per_period', models.CharField(default=';', max_length=512)),
                ('actions_list', models.CharField(default=';', max_length=512)),
                ('event_start_remainder_minutes_before', models.CharField(default=';', max_length=512)),
                ('event_end_remainder_minutes_before', models.CharField(default=';', max_length=512)),
                ('period_start_remainder_minutes_before', models.CharField(default=';', max_length=512)),
                ('period_end_remainder_minutes_before', models.CharField(default=';', max_length=512)),
                ('coin_toss_remainder_minutes_before', models.CharField(default=';', max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(default=';', max_length=512)),
                ('status', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=512)),
                ('events_ids', models.CharField(default=';', max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_name', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='TextString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_id', models.CharField(default='', max_length=512)),
                ('position_index', models.IntegerField(default=-1)),
                ('language_1', models.CharField(blank=True, max_length=512)),
                ('language_2', models.CharField(blank=True, max_length=512)),
                ('language_3', models.CharField(blank=True, max_length=512)),
                ('language_4', models.CharField(blank=True, max_length=512)),
                ('language_5', models.CharField(blank=True, max_length=512)),
            ],
        ),
    ]
