# Generated by Django 4.0.3 on 2022-03-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_botuser_event_passwordpair_rulesset_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('epoch', models.CharField(default='', max_length=512)),
                ('content_type', models.CharField(default='remainder', max_length=512)),
                ('content_id', models.IntegerField(default=-1)),
                ('content_formatters', models.CharField(default='', max_length=512)),
                ('is_sent', models.IntegerField(default=0)),
            ],
        ),
    ]
