# Generated by Django 4.0.3 on 2022-05-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_botuser_blocked_for_new_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulesset',
            old_name='interval_between_periods_munutes',
            new_name='interval_between_periods_minutes',
        ),
    ]
