# Generated by Django 4.0.3 on 2022-03-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_rename_en_textstring_language_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_name', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='language_code',
        ),
        migrations.AddField(
            model_name='botuser',
            name='language_id',
            field=models.IntegerField(default=0),
        ),
    ]
