# Generated by Django 4.0.3 on 2022-03-18 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0003_textlanguage_remove_botuser_language_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordpair',
            old_name='pasword_sha256',
            new_name='password_sha256',
        ),
    ]
