# Generated by Django 4.0.3 on 2022-05-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0003_rename_interval_between_periods_munutes_rulesset_interval_between_periods_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulesset',
            name='side_changes_during_periods_scores',
        ),
    ]
