# Generated by Django 4.0.3 on 2022-03-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0004_scheduledmessage_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='pause_epoch',
            field=models.CharField(default='', max_length=512),
        ),
    ]
