# Generated by Django 4.0.3 on 2022-03-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0004_rename_pasword_sha256_passwordpair_password_sha256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='is_logged_in',
            field=models.IntegerField(default=0),
        ),
    ]
