# Generated by Django 4.0.3 on 2022-03-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0005_scheduledmessage_pause_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='messages_ids',
            field=models.CharField(default=';', max_length=512),
        ),
    ]
