# Generated by Django 4.0.3 on 2022-03-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0005_alter_botuser_is_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='is_superadmin',
            field=models.IntegerField(default=0),
        ),
    ]
