# Generated by Django 4.0.3 on 2022-03-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0006_scheduledmessage_messages_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(default=';', max_length=512)),
                ('status', models.IntegerField(default=0)),
                ('event_id', models.IntegerField(default=-1)),
                ('period_id', models.IntegerField(default=-1)),
                ('team_id', models.IntegerField(default=-1)),
                ('type_id', models.IntegerField(default=-1)),
                ('epoch_time', models.CharField(default='', max_length=512)),
                ('at_score', models.CharField(default='', max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoinToss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(default=';', max_length=512)),
                ('status', models.IntegerField(default=0)),
                ('event_id', models.IntegerField(default=-1)),
                ('epoch_scheduled', models.CharField(default='', max_length=512)),
                ('epoch_actual', models.CharField(default='', max_length=512)),
                ('before_period_id', models.IntegerField(default=-1)),
                ('left_team_id', models.IntegerField(default=-1)),
                ('ball_possesion', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(default=';', max_length=512)),
                ('status', models.IntegerField(default=0)),
                ('event_id', models.IntegerField(default=-1)),
                ('epoch_scheduled_start', models.CharField(default='', max_length=512)),
                ('epoch_scheduled_end', models.CharField(default='', max_length=512)),
                ('epoch_actual_start', models.CharField(default='', max_length=512)),
                ('epoch_actual_end', models.CharField(default='', max_length=512)),
                ('left_team_id', models.IntegerField(default=-1)),
                ('right_team_id', models.IntegerField(default=-1)),
                ('score', models.CharField(default='', max_length=5096)),
                ('is_paused', models.IntegerField(default=0)),
                ('ball_possesion', models.IntegerField(default=-1)),
                ('time_outs_ids', models.CharField(default=';', max_length=5096)),
                ('points_ids', models.CharField(default=';', max_length=5096)),
                ('actions_ids', models.CharField(default=';', max_length=5096)),
                ('side_changes_ids', models.CharField(default=';', max_length=5096)),
                ('timers_ids', models.CharField(default=';', max_length=5096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(default=';', max_length=512)),
                ('status', models.IntegerField(default=0)),
                ('event_id', models.IntegerField(default=-1)),
                ('period_id', models.IntegerField(default=-1)),
                ('at_score', models.CharField(default='', max_length=512)),
                ('epoch_time', models.CharField(default='', max_length=512)),
                ('point_type', models.IntegerField(default=-1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SideChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(default=';', max_length=512)),
                ('status', models.IntegerField(default=0)),
                ('event_id', models.IntegerField(default=-1)),
                ('period_id', models.IntegerField(default=-1)),
                ('at_score', models.CharField(default='', max_length=512)),
                ('epoch_time', models.CharField(default='', max_length=512)),
                ('left_team_after_id', models.IntegerField(default=-1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(default=';', max_length=512)),
                ('status', models.IntegerField(default=0)),
                ('is_technical', models.IntegerField(default=0)),
                ('event_id', models.IntegerField(default=-1)),
                ('period_id', models.IntegerField(default=-1)),
                ('at_score', models.CharField(default='', max_length=512)),
                ('epoch_time', models.CharField(default='', max_length=512)),
                ('team_id', models.IntegerField(default=-1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
