# Generated by Django 4.0.3 on 2022-03-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0006_botuser_is_superadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.JSONField(default={'by': -1, 'time': 1647779634})),
                ('status', models.IntegerField(default=0)),
                ('admin_id', models.IntegerField(default=-1)),
                ('epoch_scheduled', models.IntegerField(default=-1)),
                ('epoch_actual', models.IntegerField(default=-1)),
                ('competition_name', models.CharField(default=';', max_length=512)),
                ('rules_set_id', models.IntegerField(default=-1)),
                ('home_team_id', models.IntegerField(default=-1)),
                ('away_team_id', models.IntegerField(default=-1)),
                ('periods_ids', models.CharField(default=';', max_length=5096)),
                ('coin_toss_ids', models.CharField(default=';', max_length=5096)),
                ('timer_ids', models.CharField(default=';', max_length=5096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RulesSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.JSONField(default={'by': -1, 'time': 1647779634})),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.JSONField(default={'by': -1, 'time': 1647779634})),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='botuser',
            name='remainders_ids',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='screen_messages_ids',
            field=models.CharField(default=';', max_length=512),
        ),
    ]
