# Generated by Django 4.0.3 on 2022-03-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0007_event_rulesset_team_alter_botuser_remainders_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.JSONField(default={'by': -1, 'time_': 1647779709}),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='created',
            field=models.JSONField(default={'by': -1, 'time_': 1647779709}),
        ),
        migrations.AlterField(
            model_name='team',
            name='created',
            field=models.JSONField(default={'by': -1, 'time_': 1647779709}),
        ),
    ]
