# Generated by Django 4.0.3 on 2022-03-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0007_action_cointoss_period_point_sidechange_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active_status',
            field=models.IntegerField(default=1),
        ),
    ]
