# Generated by Django 4.0.3 on 2022-03-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0008_event_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='content_callback',
            field=models.CharField(default='', max_length=512),
        ),
    ]
