# Generated by Django 4.0.3 on 2022-03-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0008_alter_event_created_alter_rulesset_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='created',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='team',
            name='created',
            field=models.JSONField(default=dict),
        ),
    ]
