# Generated by Django 4.0.3 on 2022-03-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0009_scheduledmessage_content_callback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cointoss',
            old_name='ball_possesion',
            new_name='ball_possesion_team_id',
        ),
        migrations.RemoveField(
            model_name='cointoss',
            name='before_period_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_actual',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time_actual',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timer_ids',
        ),
        migrations.AddField(
            model_name='cointoss',
            name='before_period',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='score',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='event',
            name='score_sum',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='event',
            name='side_changes_ids',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_scheduled',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_scheduled',
            field=models.CharField(default='', max_length=512),
        ),
    ]
