# Generated by Django 4.0.3 on 2022-03-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0010_rename_ball_possesion_cointoss_ball_possesion_team_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='at_score',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='action',
            name='created',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='action',
            name='epoch_time',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='current_screen_code',
            field=models.CharField(default='00', max_length=5096),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='remainders_ids',
            field=models.CharField(default='{}', max_length=5096),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='screen_messages_ids',
            field=models.CharField(default='{}', max_length=5096),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='tg_id',
            field=models.CharField(blank=True, max_length=5096),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_input_messages_ids',
            field=models.CharField(default='{}', max_length=5096),
        ),
        migrations.AlterField(
            model_name='cointoss',
            name='created',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='cointoss',
            name='epoch_actual',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='cointoss',
            name='epoch_scheduled',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='competition',
            name='created',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='competition',
            name='events_ids',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_scheduled',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='event',
            name='score',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='event',
            name='score_sum',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_scheduled',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='passwordpair',
            name='password_sha256',
            field=models.CharField(max_length=5096),
        ),
        migrations.AlterField(
            model_name='period',
            name='created',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='period',
            name='epoch_actual_end',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='period',
            name='epoch_actual_start',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='period',
            name='epoch_scheduled_end',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='period',
            name='epoch_scheduled_start',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='point',
            name='at_score',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='point',
            name='created',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='point',
            name='epoch_time',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='actions_list',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='coin_toss_remainder_minutes_before',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='coin_toss_start_before_minutes',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='coin_tosses_before_periods',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='created',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='event_end_remainder_minutes_before',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='event_start_remainder_minutes_before',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='interval_between_periods_munutes',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='min_difference_points_to_win_period',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='name',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='period_end_remainder_minutes_before',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='period_start_remainder_minutes_before',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='period_timers_directions',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='period_timers_stop_at_pauses',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='periods_lenght_minutes',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='points_per_score_per_period',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='points_to_win_period',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='scores_names',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='side_changes_after_periods',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='side_changes_during_periods',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='side_changes_during_periods_pause_time_seconds',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='side_changes_during_periods_scores',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='technical_time_outs_at_score_per_period',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='technical_time_outs_lenghts_per_period',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='time_outs_lenghts_per_team_per_period',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='time_outs_per_team_per_period',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='win_period_by',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='content_callback',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='content_formatters',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='content_type',
            field=models.CharField(default='remainder', max_length=5096),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='epoch',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='group_name',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='messages_ids',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='pause_epoch',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='sidechange',
            name='at_score',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='sidechange',
            name='created',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='sidechange',
            name='epoch_time',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='team',
            name='created',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='team',
            name='events_ids',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='textlanguage',
            name='self_name',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='textstring',
            name='language_1',
            field=models.CharField(blank=True, max_length=5096),
        ),
        migrations.AlterField(
            model_name='textstring',
            name='language_2',
            field=models.CharField(blank=True, max_length=5096),
        ),
        migrations.AlterField(
            model_name='textstring',
            name='language_3',
            field=models.CharField(blank=True, max_length=5096),
        ),
        migrations.AlterField(
            model_name='textstring',
            name='language_4',
            field=models.CharField(blank=True, max_length=5096),
        ),
        migrations.AlterField(
            model_name='textstring',
            name='language_5',
            field=models.CharField(blank=True, max_length=5096),
        ),
        migrations.AlterField(
            model_name='textstring',
            name='screen_id',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='timeout',
            name='at_score',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AlterField(
            model_name='timeout',
            name='created',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='timeout',
            name='epoch_time',
            field=models.CharField(default='', max_length=5096),
        ),
    ]
