# Generated by Django 4.0.3 on 2022-03-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0010_remove_event_created_remove_rulesset_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulesset',
            old_name='competition_name',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='competition_name',
            new_name='created',
        ),
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.CharField(default=';', max_length=512),
        ),
    ]
