# Generated by Django 4.0.3 on 2022-03-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0011_rename_competition_name_rulesset_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(default=';', max_length=512)),
                ('status', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=512)),
                ('events_ids', models.CharField(default=';', max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='competition_name',
        ),
        migrations.AddField(
            model_name='event',
            name='event_competition_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='actions_list',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='coin_toss_remainder_minutes_before',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='coin_toss_start_before_minutes',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='coin_tosses_before_periods',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='created_by',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='event_end_remainder_minutes_before',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='event_length_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='event_start_remainder_minutes_before',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='event_timer_direction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='event_timer_stops_at_pauses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='interval_between_periods_munutes',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='min_difference_periods_to_win_event',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='min_difference_points_to_win_period',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='period_end_remainder_minutes_before',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='period_start_remainder_minutes_before',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='period_timers_directions',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='period_timers_stop_at_pauses',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='periods_in_event',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='periods_lenght_minutes',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='periods_to_win_event',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='points_in_period',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='points_per_score_per_period',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='points_to_win_period',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='scores_names',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='side_changes_after_periods',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='side_changes_during_periods',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='side_changes_during_periods_pause_time_seconds',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='side_changes_during_periods_scores',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='stop_event_after_enough_periods',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='stop_period_after_enough_points',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='technical_time_outs_at_score_per_period',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='technical_time_outs_lenghts_per_period',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='time_outs_lenghts_per_team_per_period',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='time_outs_per_team_per_period',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='win_event_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rulesset',
            name='win_period_by',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='team',
            name='events_ids',
            field=models.CharField(default=';', max_length=512),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=512),
        ),
    ]
