# Generated by Django 4.0.3 on 2022-03-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0011_alter_action_at_score_alter_action_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointoss',
            name='left_team_id',
            field=models.IntegerField(default=0),
        ),
    ]
