# Generated by Django 4.0.3 on 2022-03-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0012_alter_cointoss_left_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='score',
        ),
        migrations.RemoveField(
            model_name='event',
            name='score_sum',
        ),
        migrations.RemoveField(
            model_name='period',
            name='score',
        ),
        migrations.AddField(
            model_name='event',
            name='end_actual_epoch',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AddField(
            model_name='event',
            name='end_scheduled_epoch',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AddField(
            model_name='event',
            name='start_actual_epoch',
            field=models.CharField(default='', max_length=5096),
        ),
        migrations.AddField(
            model_name='event',
            name='start_scheduled_epoch',
            field=models.CharField(default='', max_length=5096),
        ),
    ]
