# Generated by Django 4.0.3 on 2022-03-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0013_remove_event_score_remove_event_score_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='team_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='point',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
