# Generated by Django 4.0.3 on 2022-03-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0013_remove_event_event_competition_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='delete_away_team_name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='event',
            name='delete_competition_name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='event',
            name='delete_date',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='event',
            name='delete_home_team_name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='event',
            name='delete_time',
            field=models.CharField(default='', max_length=512),
        ),
    ]
