# Generated by Django 4.0.3 on 2022-03-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0014_event_delete_away_team_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(default=';', max_length=5096),
        ),
    ]
