# Generated by Django 4.0.3 on 2022-03-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0015_rename_epoch_actual_end_period_end_actual_epoch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='ball_possesion',
            new_name='ball_possesion_team_id',
        ),
        migrations.RemoveField(
            model_name='rulesset',
            name='event_timer_stops_at_pauses',
        ),
        migrations.RemoveField(
            model_name='rulesset',
            name='period_timers_stop_at_pauses',
        ),
        migrations.RemoveField(
            model_name='rulesset',
            name='side_changes_during_periods_pause_time_seconds',
        ),
        migrations.AddField(
            model_name='rulesset',
            name='timers_stop_at_pauses',
            field=models.IntegerField(default=0),
        ),
    ]
