# Generated by Django 4.0.3 on 2022-03-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0016_rename_ball_possesion_period_ball_possesion_team_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='point_type',
            new_name='type',
        ),
    ]
