# Generated by Django 4.0.3 on 2022-03-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0017_rename_point_type_point_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='time_outs_ids',
            new_name='timeouts_ids',
        ),
    ]
