# Generated by Django 4.0.3 on 2022-03-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0018_rename_time_outs_ids_period_timeouts_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='timers_ids',
        ),
    ]
