# Generated by Django 4.0.3 on 2022-03-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0019_remove_period_timers_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesset',
            name='stop_period_after_enough_points',
            field=models.CharField(default=';', max_length=5096),
        ),
    ]
