# Generated by Django 4.0.3 on 2022-03-29 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0021_period_orgiginal_ball_possesion_team_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='orgiginal_ball_possesion_team_id',
            new_name='original_ball_possesion_team_id',
        ),
    ]
