# Generated by Django 4.0.3 on 2022-03-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0022_rename_orgiginal_ball_possesion_team_id_period_original_ball_possesion_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='coin_toss_ids',
            new_name='coin_tosses_ids',
        ),
    ]
