# Generated by Django 4.0.3 on 2022-04-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0023_rename_coin_toss_ids_event_coin_tosses_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTemplateEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(default=';', max_length=5096)),
                ('status', models.IntegerField(default=0)),
                ('event_id', models.IntegerField(default=-1)),
                ('field_name', models.CharField(max_length=5096)),
                ('old_value', models.CharField(max_length=5096)),
                ('new_value', models.CharField(max_length=5096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='actions_list',
            field=models.CharField(default='()', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='coin_tosses_before_periods',
            field=models.CharField(default='()', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='scores_names',
            field=models.CharField(default='()', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='time_outs_per_team_per_period',
            field=models.CharField(default='()', max_length=5096),
        ),
    ]
