# Generated by Django 4.0.3 on 2022-04-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0024_eventtemplateedit_alter_rulesset_actions_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='created',
            field=models.CharField(default='{}', max_length=5096),
        ),
        migrations.AlterField(
            model_name='cointoss',
            name='created',
            field=models.CharField(default='{}', max_length=5096),
        ),
        migrations.AlterField(
            model_name='competition',
            name='created',
            field=models.CharField(default='{}', max_length=5096),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.CharField(default='{}', max_length=5096),
        ),
        migrations.AlterField(
            model_name='eventtemplateedit',
            name='created',
            field=models.CharField(default='{}', max_length=5096),
        ),
        migrations.AlterField(
            model_name='period',
            name='created',
            field=models.CharField(default='{}', max_length=5096),
        ),
        migrations.AlterField(
            model_name='point',
            name='created',
            field=models.CharField(default='{}', max_length=5096),
        ),
        migrations.AlterField(
            model_name='rulesset',
            name='created',
            field=models.CharField(default='{}', max_length=5096),
        ),
        migrations.AlterField(
            model_name='sidechange',
            name='created',
            field=models.CharField(default='{}', max_length=5096),
        ),
        migrations.AlterField(
            model_name='team',
            name='created',
            field=models.CharField(default='{}', max_length=5096),
        ),
        migrations.AlterField(
            model_name='timeout',
            name='created',
            field=models.CharField(default='{}', max_length=5096),
        ),
    ]
