from .AuthorizationInvitation import AuthorizationInvitation
from .AuthorizationWrongPassword import AuthorizationWrongPassword

authorization_screens = [AuthorizationInvitation, AuthorizationWrongPassword]